@startuml articulos

package articulos <<Folder>> #F9E79F {
    MenuArticulos <|-- AddArticulos
    MenuArticulos <|-- DelArticulos
    MenuArticulos <|-- LisArticulos
    LisArticulos <|-- ModArticulos

    class MenuArticulos #F6DDCC{
        + master : Tk
        - _app
        + almacen_articulos
        + almacen_clientes
        + ventana_add_articulos : AddArticulos
        + ventana_del_articulos : DelArticulos
        + ventana_lis_articulos : LisArticulos
        + title_articulos
        + boton_add_articulos
        + boton_del_articulos
        + boton_lis_articulos
        + __init__(self, master, ...)
        + mostrar_menu(self)
        + ocultar_menu(self)
        + on_close(self)
        + abrir_ventana_add_articulos(self)
        + abrir_ventana_del_articulos(self)
        + abrir_ventana_lis_articulos(self)   
}
    class AddArticulos #F6DDCC{
        + menu_articulos
        + PLACEHOLDER_COD_CLIENTE : str
        + PLACEHOLDER_NOMBRE : str
        + PLACEHOLDER_DESCRIPCION : str
        + PLACEHOLDER_CATEGORIA : str
        + cod_cliente_seleccionado
        + input_nombre_seleccionado
        + input_descripcion_seleccionada
        + categoria_seleccionada
        + title_add_articulos
        + print_cod_cliente
        + eleccion_cod_cliente
        + print_nombre
        + input_nombre
        + print_descripcion
        + input_descripcion
        + print_categoria
        + posibles_categorias
        + eleccion_categorias
        + boton_add_articulos
        + __init__(self, master, ...)
        + actualizar_posibles_cod_cliente(self)
        + recoger_datos_articulos(self)
        + comprobar_articulos(self)
        + clear_placeholder_eleccion_cod_cliente(self, event)
        + set_placeholder_eleccion_cod_cliente(self, event)
        + clear_placeholder_input_nombre(self, event)
        + set_placeholder_input_nombre(self, event)
        + clear_placeholder_input_descripcion(self, event)
        + set_placeholder_input_descripcion(self, event)
        + clear_placeholder_input_categoria(self, event)
        + set_placeholder_input_categoria(self, event)
        + limpiar_campos(self)

}
    class DelArticulos #F6DDCC{
        + menu_articulos
        + PLACEHOLDER_COD_ARTICULO: str
        + title_del_articulos
        + print_cod_articulo
        + eleccion_cod_articulo
        + boton_del_articulos
        + __init__(self, master, ...)
        + actualizar_posibles_cod_articulo(self)
        + tratar_del_articulo(self)
        + clear_placeholder_eleccion_cod_articulo(self, event)
        + set_placeholder_eleccion_cod_articulo(self, event)
        + limpiar_campos(self)
}
    class LisArticulos #F6DDCC{
        + almacen_clientes
        + menu_articulos
        + IMAGEN_MICRO
        + foto_micro
        + style
        + cod_articulo_var
        + cod_cliente_var
        + nombre_var
        + descripcion_var
        + categoria_var
        + ventana_mod_articulos : ModArticulos
        + title_lis_sucursales
        + tree_articulos
        + print_filtro
        + input_filtro
        + boton_microfono
        + boton_mod_articulos
        + tree_articulos
        + __init__(self, master, ...)
        + crear_listado(self)
        + realizar_busqueda(self, event)
        + recoger_datos(self)
        + recoger_audio(self)
        + on_select(self, event)
        + ocultar_menu(self)
        + abrir_ventana_mod_articulos(self)
}
    class ModArticulos #F6DDCC{
        + menu_lis_articulos
        + print_cod_articulo
        + input_cod_articulo
        + print_cod_cliente
        + eleccion_cod_cliente
        + print_nombre
        + input_nombre
        + print_descripcion
        + input_descripcion
        + print_categoria
        + posibles_categorias
        + eleccion_categorias
        + boton_mod_articulos
        + __init__(self, master, ...)
        + mostrar_menu(self)
        + actualizar_posibles_cod_cliente(self)
        + realizar_modificaciones(self)
        + on_close(self)
    }
}
@enduml

