@startuml hmnlogistics
package gui <<Folder>> #F9E79F {
    class MenuHmn #F6DDCC{
    + master : Tk
    + app
    + almacen_articulos: AlmacenArticulos
    + almacen_clientes: AlmacenClientes
    + almacen_sucursales: ALmacenSucursales
    + almacen_distribuidores: AlmacenDistribuidores
    + almacen_pedidos: AlmacenPedidos
    + almacen_departamentos: AlmacenDepartamentos
    + almacen_empleados: AlmacenEmpleados
    + ventana_articulo: MenuArticulos
    + ventana_cliente: MenuCliente
    + ventana_sucursal: MenuSucursales
    + ventana_distribuidor: MenuDistribuidores
    + ventana_pedidos: MenuPedidos
    + ventana_departamentos: MenuDepartamentos
    + ventana_empleados: MenuEmpleados
    + IMAGEN_FAVICON
    + resized_favicon
    + favicon_tk
    + IMAGEN_LOGO
    + resized_logo_hmn
    + logo_hmn
    + logo_hmn_menu
    + title_hmn
    + subtitulo_hmn
    + boton_articulos
    + boton_clientes
    + boton_sucursales
    + boton_pedidos
    + boton_distribuidores
    + boton_departamentos
    + boton_empleados
    + guardar_datos
    + guardar_salir
    + ocultar_menu(self)
    + acceder_menu_articulos(self)
    + acceder_menu_clientes(self)
    + acceder_menu_sucursales(self)
    + acceder_menu_distribuidores(self)
    + acceder_menu_pedidos(self)
    + acceder_menu_departamentos(self)
    + acceder_menu_empleados(self)
    + on_close(self)
    + clickar_boton_guardar(self)
    + clickar_boton_guardar_salir(self)
    + recoger_datos(self)
    
}
package articulos <<Folder>> #F9E79F {
    MenuHmn <|-- MenuArticulos
    class MenuArticulos #F6DDCC{}
}
package clientes <<Folder>> #F9E79F {
    MenuHmn <|-- MenuClientes
    class MenuClientes #F6DDCC{}
}
package departamentos <<Folder>> #F9E79F {
    MenuHmn <|-- MenuDepartamentos
    class MenuDepartamentos #F6DDCC{}
}
package sucursales <<Folder>> #F9E79F {
    MenuHmn <|-- MenuSucursales
    class MenuSucursales #F6DDCC{}
}
package distribuidores <<Folder>> #F9E79F {
    MenuHmn <|-- MenuDistribuidores
    class MenuDistribuidores #F6DDCC{}
}
package pedidos <<Folder>> #F9E79F {
    MenuHmn <|-- MenuPedidos
    class MenuPedidos #F6DDCC{}
}
package empleados <<Folder>> #F9E79F {
    MenuHmn <|-- MenuEmpleados
    class MenuEmpleados #F6DDCC{}
}
}
package cnx <<Folder>> #F9E79F {
    MenuHmn --> Inserts
    class Inserts #F6DDCC{
        + cnx
        + DELETE_PREVIO_DEPARTAMENTOS
        + DELETE_PREVIO_PEDIDOS
        + DELETE_PREVIO_DISTRIBUIDORES
        + DELETE_PREVIO_SUCURSALES
        + DELETE_PREVIO_CLIENTES
        + DELETE_PREVIO_ARTICULOS
        + DELETE_PREVIO_DATOS_EMPLEADOS
        + DELETE_PREVIO_EMPLEADOS
        + CAMPO_0
        + CAMPO_1
        + CAMPO_2
        + CAMPO_3
        + CAMPO_4
        + CAMPO_5
        + CAMPO_6
        + ConstanteCampos.opciones()
        + realizar_deletes(self)
        + cargar_bbdd_distribuidores(self)
        + cargar_bbdd_sucursales(self)
        + cargar_bbdd_clientes(self)
        + cargar_bbdd_articulos(self)
        + cargar_bbdd_pedidos(self)
        + cargar_bbdd_departamentos(self)
        + cargar_bbdd_datos_empleados(self)
        + cargar_bbdd_empleados(self)

        
}
}
package almacen <<Folder>> #F9E79F {
    MenuHmn --> AlmacenArticulos
    MenuHmn --> AlmacenClientes
    MenuHmn --> AlmacenDepartamentos
    MenuHmn --> AlmacenDistribuidores
    MenuHmn --> AlmacenEmpleados
    MenuHmn --> AlmacenPedidos
    MenuHmn --> AlmacenSucursales
    class AlmacenArticulos #F6DDCC{}
    class AlmacenClientes #F6DDCC{}
    class AlmacenDepartamentos #F6DDCC{}
    class AlmacenDistribuidores #F6DDCC{}
    class AlmacenEmpleados #F6DDCC{}
    class AlmacenPedidos #F6DDCC{}
    class AlmacenSucursales #F6DDCC{}
}
@enduml
