@startuml pedidos

package pedidos <<Folder>> #F9E79F {
    MenuPedidos <|-- AddPedidos
    MenuPedidos <|-- DelPedidos
    MenuPedidos <|-- LisPedidos
    LisPedidos <|-- ModPedidos

    together {
  class AddPedidos
  class DelPedidos
  class LisPedidos
}
    
    class MenuPedidos #F6DDCC{
        + master
        - _app
        + almacen_pedidos
        + almacen_distribuidores
        + almacen_sucursales
        + ventana_add_pedidos
        + ventana_lis_pedidos
        + title_pedidos
        + boton_add_pedidos
        + boton_del_pedidos
        + boton_lis_pedidos
        + __init__(self, master, ...)
        + mostrar_menu(self)
        + ocultar_menu(self)
        + on_close(self)
        + abrir_ventana_add_pedidos(self)
        + abrir_ventana_del_pedidos(self)
        + abrir_ventana_lis_pedidos(self)
}
    class AddPedidos #F6DDCC{
        + menu_pedidos
        + no_mostrar_calendario : Boolean
        + validador : Validator
        + PLACEHOLDER_COD_DISTRIBUIDOR : str
        + PLACEHOLDER_COD_SUCURSAL : str
        + PLACEHOLDER_NUM_ARTICULOS : str
        + PLACEHOLDER_PESO : str
        + PLACEHOLDER_PRECIO : str
        + cod_distribuidor_seleccionado
        + cod_sucursal_seleccionado
        + input_num_articulos
        + input_peso_seleccionado
        + input_precio_seleccionado
        + title_add_pedidos
        + print_cod_distribuidor
        + eleccion_cod_distribuidor
        + print_cod_sucursal
        + eleccion_cod_distribuidor
        + print_fecha_pedido
        + input_fecha_pedido
        + print_num_articulos
        + input_num_articulos
        + print_peso
        + input_peso
        + print_precio
        + input_precio
        + boton_add_pedido
        + __init__(self, master, ...)
        + actualizar_posibles_distribuidores_sucursales(self)
        + recoger_datos_pedidos(self)
        + comprobar_pedidos(self)
        + clear_placeholder_eleccion_cod_distribuidor(self, event)
        + set_placeholder_eleccion_cod_distribuidor(self, event)
        + clear_placeholder_eleccion_cod_sucursal(self, event)
        + set_placeholder_eleccion_cod_sucursal(self, event)
        + clear_placeholder_input_num_articulos(self, event)
        + set_placeholder_input_num_articulos(self, event)
        + clear_placeholder_input_peso(self, event)
        + set_placeholder_input_peso(self, event)
        + clear_placeholder_input_precio(self, event)
        + set_placeholder_input_precio(self, event)
        + limpiar_campos(self)     
}
    class DelPedidos #F6DDCC{
        + menu_pedidos
        + PLACEHOLDER_COD_PEDIDO : str
        + cod_pedido_seleccionado
        + title_del_pedidos
        + print_cod_pedido
        + eleccion_cod_pedido
        + boton_del_pedido
        + __init__(self, master, ...)
        + actualizar_posibles_cod_pedido(self)
        + tratar_del_pedido(self)
        + clear_placeholder_eleccion_cod_pedido(self, event)
        + set_placeholder_eleccion_cod_pedido(self, event)
        + limpiar_campos(self)
}
    class LisPedidos #F6DDCC{
        + menu_pedidos
        + IMAGEN_MICRO
        + foto_micro
        + style
        + cod_pedido_var
        + cod_distribuidor_var
        + cod_sucursal_var
        + fecha_pedido_var
        + cantidad_articulos_var
        + peso_var
        + precio_var
        + ventana_mod_pedidos : ModPedidos
        + title_lis_pedidos
        + tree_pedidos
        + input_filtro
        + print_filtro
        + boton_microfono
        + boton_mod_pedidos
        + __init__(self, master, ...)
        + crear_listado(self)
        + realizar_busqueda(self, event)
        + recoger_datos(self)
        + recoger_audio(self)
        + on_select(self, event)
        + abrir_ventana_mod_pedidos(self)
}
    class ModPedidos #F6DDCC{
        + menu_lis_pedidos
        + no_mostrar_calendario : Boolean
        + validador : Validator
        + print_cod_pedido
        + input_cod_pedido
        + print_cod_distribuidor
        + eleccion_cod_distribuidor
        + print_cod_sucursal
        + eleccion_cod_sucursal
        + print_fecha_pedido
        + input_fecha_pedido
        + print_cantidad_articulos
        + input_cantidad_articulos
        + print_peso
        + input_peso
        + print_precio
        + input_precio
        + boton_mod_pedidos
        + __init__(self, master, ...)
        + actualizar_posibles_combobox(self)
        + realizar_modificaciones(self)
}
}

package clases <<Folder>> #F9E79F{
    ModPedidos --> Validator : A tener en cuenta
    note on link : Solo reflejo los atributos y métodos\nnecesarios para este directorio.
    AddPedidos --> Validator 
    
    class Validator #F6DDCC{ 
        + formato_es_numero
        + validador_es_numero(self, dato_introducido: str)
}
}
@enduml

